name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: optigate_api_test
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Wait for PostgreSQL service to start
        run: |
          until nc -z localhost 5432; do
            echo "Waiting for PostgreSQL service..."
            sleep 1
          done

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install compile-time dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential openssh-client libpq-dev

      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # - name: Load database schema
      #   run: bundle exec rails db:schema:load --trace

      - name: Run RSpec
        run: |
          bundle exec rspec \
            --profile 10 \
            --format RspecJunitFormatter \
            --out test_results/rspec.xml \
            --format documentation

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test # This job will not start until the "test" job has successfully completed
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_email: "syedanabimam@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "optigate"
